default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: henri-weather-app_development

test:
  <<: *default
  database: henri-weather-app_test

production:
  <<: *default
  database: dbfrorp88528ep
  username: psavqsfibaccmzntjaomgecmdgpi
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host:     ec2-107-20-243-220.compute-1.amazonaws.com
